'use client';
import {useEffect,useState} from 'react';

const logo='/WVLogo.webp';
const video='/VideoVM.mp4';
const news=[
 ['/research-1.jpg','REPORTS & PUBLICATIONS','Community research on the health and social needs of Black and minoritised women aged 50+'],
 ['/group.png','TRAINING','Confidence building, ESOL, wellbeing, legal rights, social enterprise skills and peer mentoring'],
 ['/488648071_1135728305263676_4533181307934619130_n.jpg','OUR STORIES','Women sharing experiences of care, creativity, resilience and finding a family through Women’s Voices']
];
const pillars=[['/group.png','TRAINING','We offer practical learning opportunities that build confidence, communication, wellbeing, rights awareness and enterprise skills.'],['/Nadia.png','VOLUNTEERING','Volunteers share skills, support drop-in sessions, raise the profile of Women’s Voices CIC and help organise events.'],['/wv-leadership.jpg','COMMUNITY','We provide a safe, accessible space where women can meet, learn, build resilience and strengthen their independence.']];

function Header(){const [open,setOpen]=useState(false);const [mega,setMega]=useState('');useEffect(()=>{document.body.style.overflow=open?'hidden':'';return()=>{document.body.style.overflow=''}},[open]);return <><header><a className="mark"><img src={logo} alt="Women’s Voices"/></a><nav>{['ABOUT','TRAINING','VOLUNTEERING','REPORTS','STORIES','CONTACT'].map((x,i)=><button key={x} onMouseEnter={()=>setMega(i===0?'ABOUT':i===3?'REPORTS':i===5?'CONTACT':'')} onMouseLeave={()=>setMega('')}>{(i===0||i===5)&&'⌄ '}{x}</button>)}<a className="partner">SUPPORT OUR WORK</a><a className="login">CONTACT <b>→</b></a></nav><button className={`hamb ${open?'on':''}`} onClick={()=>setOpen(!open)}><i/><i/><span>{open?'CLOSE':'MENU'}</span></button></header>
<div className={`mega ${mega?'show':''}`} onMouseEnter={()=>setMega(mega)} onMouseLeave={()=>setMega('')}><h2>{mega}</h2>{(mega==='ABOUT'?['Who we are','Aims and vision','Activities','Partner organisations']:mega==='REPORTS'?['Community research project','Creative writing and food','Downloads','Publications']:['Email us','Visit the Burhan Centre','Contact and social media']).map(x=><a key={x}>{x}<b>↗</b></a>)}</div>
<aside className={`drawer ${open?'show':''}`}><div className="drawer-in">{['ABOUT','TRAINING','VOLUNTEERING','REPORTS','STORIES','CONTACT'].map((x,i)=><a key={x}><em>0{i+1}</em>{x}<b>→</b></a>)}<a className="outline">SUPPORT OUR WORK</a><a className="outline">CONTACT</a></div></aside></>}

export default function Home(){return <main><Header/><section className="hero"><video autoPlay muted loop playsInline src={video}/><div className="shade"/><div className="hero-center"><h1>Women&apos;s Voices</h1><h2>Empowering women in our community</h2></div></section><div className="ticker"><div>{Array(8).fill('TRAINING . VOLUNTEERING . STORIES . SUPPORT →').map((x,i)=><span key={i}>{x}</span>)}</div></div>
<section className="who"><div className="who-title"><span>ABOUT US</span><h2>WHO<br/>WE ARE</h2></div><div className="who-copy"><p>Women’s Voices is a not-for-profit organisation based in Longsight, Manchester. Since 2013, it has created a safe and accessible place for women to meet, learn, develop skills, build confidence and grow their independence.</p><div><a>OUR AIMS ↗</a><a>CONTACT US ↗</a><a>OUR PARTNERS ↗</a></div></div></section>
<section className="latest"><div className="section-head"><h2>WHAT WE DO</h2><a>VIEW ALL <b>→</b></a></div><div className="news-grid">{news.map(([img,kicker,title],i)=><article key={title} className={`n${i}`}><div className="news-img" style={{backgroundImage:`url(${img})`}}><span>0{i+1}</span></div><small>{kicker}</small><h3>{title}</h3><p>Women’s Voices works with women seeking asylum, refugees and vulnerable women from diverse backgrounds in Longsight, Manchester.</p><a>MORE INFORMATION →</a></article>)}</div></section>
<section className="impact"><h2>OUR ACTIVITIES</h2><div className="pillar-grid">{pillars.map(([img,h,p],i)=><article key={h}><span>0{i+1}</span><img src={img} alt=""/><h3>{h}</h3><p>{p}</p><a>DISCOVER →</a></article>)}</div></section>
<section className="connected"><div className="social-panel"><small>CONTACT AND SOCIAL MEDIA</small><h2>Find us on<br/><b>FACEBOOK AND TWITTER</b></h2><div className="socials"><i>in</i><i>f</i><i>◎</i><i>▶</i></div></div><div className="community"><small>VOLUNTEERING</small><h2>Support<br/><b>WOMEN’S VOICES</b></h2><p>Volunteers help us deliver services, run drop-in sessions, organise events and fundraise for our projects.</p><strong>SHARE SKILLS . BUILD CONFIDENCE . GET INVOLVED</strong><a>CONTACT US →</a></div></section>
<section className="meeting"><div className="meeting-copy"><small>AIMS AND VISION</small><h2>EMPOWERMENT,<br/>EQUALITY AND INCLUSION</h2><p>Our aim is to help break cycles of deprivation for Black, Asian, Minority Ethnic and Refugee women, while challenging barriers that prevent women from reaching their potential.</p><p>We strengthen women’s voice and influence so they can become ambassadors for other women and help change how women are viewed in communities and wider society.</p><a>READ OUR STORIES →</a></div><div className="stats"><h3>WOMEN’S VOICES<br/><b>KEY DETAILS</b></h3><div><strong>2013</strong><span>ESTABLISHED</span></div><div><strong>50+</strong><span>RESEARCH FOCUS</span></div><div><strong>CIC</strong><span>COMMUNITY ORGANISATION</span></div></div></section>
<section className="partners"><p>SUPPORTED BY AND WORKING WITH</p><div><b>BIG LOTTERY<br/>FUND</b><b>MANCHESTER<br/>MAYA PROJECT</b><b>WONDERFULLY<br/>MADE WOMAN</b><b>ANANNA</b><b>WAI YIN<br/>SOCIETY</b></div><a>SEE PARTNER ORGANISATIONS →</a></section>
<section className="newsletter"><h2>GET IN TOUCH</h2><a>ADMIN@WOMENSVOICES.ORG.UK <b>→</b></a></section>
<footer><div className="foot-top"><img src={logo} alt="Women’s Voices"/><div><h3>QUICK ACCESS</h3><a>Who we are and what we do</a><a>Reports and publications</a><a>Training and volunteering</a></div><div><small>CONTACT</small><h3>GET IN TOUCH</h3><p>Women’s Voices CIC<br/>Burhan Centre, First Floor<br/>81 Beresford Road, Longsight<br/>Manchester M13 0GX<br/>0161 225 6908</p></div></div><div className="foot-bottom"><span>Privacy & Cookies Notices　 Terms & Conditions　 Legal Mentions</span><span>© Women&apos;s Voices 2026</span></div></footer></main>}
