import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PageShell } from "@/components/page-shell";
export const metadata:Metadata={title:"Volunteering",description:"Volunteer with Women’s Voices in Manchester and share skills, support drop-ins, help at events or contribute to community projects.",alternates:{canonical:"/volunteering"}};
const opportunities=["Share skills, knowledge and experience","Support weekly drop-in sessions","Help organise activities, trips and events","Contribute to arts, crafts, sewing and food-growing sessions","Support fundraising and community outreach","Help raise the profile of Women’s Voices CIC"];
const photos=["/gallery/event-26.jpg","/gallery/event-23.jpg","/gallery/event-27.jpg","/gallery/event-24.jpg"];
const StoryImage=({src,alt}:{src:string;alt:string})=><figure className="story-image volunteering-story-image"><div><Image src={src} alt={alt} fill sizes="(max-width:900px) 100vw, 50vw"/></div></figure>;
export default function VolunteeringPage(){return <PageShell title="VOLUNTEERING" intro="Volunteers are central to our work, helping Women’s Voices operate day to day and creating a culture that supports and empowers women.">
<section className="content-section split-content"><div><span className="content-number">01</span><h2>SHARE SKILLS. BUILD CONFIDENCE.</h2></div><div className="prose"><p>Volunteers work alongside staff to help deliver services, welcome women into the centre and make community activities possible. Every drop-in, workshop and event we run depends on people giving their time, whether that is an hour a week or a regular commitment.</p><p>Many former service users go on to volunteer themselves, sharing their experience and strengthening the support available to others. For some, volunteering is the first step back into structured activity after a difficult period; for others, it is a way to put existing professional skills to use in a new country.</p><p>Whatever background you bring, we match opportunities to your interests and availability, and we always make sure new volunteers are properly welcomed, trained and supported before taking anything on alone.</p></div></section>
<StoryImage src={photos[0]} alt="Volunteers taking part in a Women’s Voices community session"/>
<section className="content-section content-dark"><span className="content-number">02</span><h2>WAYS TO CONTRIBUTE</h2><ul className="opportunity-list">{opportunities.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</li>)}</ul></section>
<StoryImage src={photos[1]} alt="Women volunteering together"/>
<section className="content-section split-content"><div><span className="content-number">03</span><h2>PART OF THE COMMUNITY</h2></div><div className="prose"><p>Volunteering creates opportunities to contribute, meet people, develop experience and help other women feel welcome and supported. It also keeps Women’s Voices rooted in real community rather than a service delivered from the outside: many of the women running sessions today first walked through our doors looking for support themselves.</p><p>If you are looking for a way to use your time, skills or lived experience meaningfully, whether that is an afternoon a month or a regular weekly slot, there is very likely a role here for you.</p></div></section>
<div className="story-image-row story-image-row--two">{photos.slice(2).map((src,i)=><figure className="story-image story-image--small volunteering-story-image" key={src}><div><Image src={src} alt={["Community volunteers at Women’s Voices","Women’s Voices volunteers and community members"][i]} fill sizes="(max-width:900px) 100vw, 50vw"/></div></figure>)}</div>
<section className="content-cta"><div><h2>TELL US ABOUT YOUR INTERESTS AND AVAILABILITY</h2></div><Link href="/contact">BECOME A VOLUNTEER →</Link></section>
</PageShell>}